### ISSUE TITLE
Allinone for switch

### ISSUE THREAD

**Issue by luisleonardo** [ualex73/monitor_docker#102]
Hi,

Is it possible to add an option to have the attributes from the sensor in the switch? This would help a lot to create a dynamic list in a card with memory, cpu, status and the ability to turn on/off the containers.

Thanks.

**Comment by ualex73** [comment]
It is not that issue to do this, because it is 2 different types (and next to it is possible, it will duplicate the code base). So for now, it is not possible and I will close the ticket.
