### ISSUE TITLE
No module named 'aiodocker' on HA 2022.7.1

### ISSUE THREAD

**Issue by acurrington** [ualex73/monitor_docker#105]
After upgrading to Home Assistant 2022.7.1 I have this message appearing now when I do a check config in developer tools. 

Component error: monitor_docker - No module named 'aiodocker'

Looks like it's broken with the recent HA update. Any ideas how to resolve?

**Comment by ualex73** [comment]
I just tested it with version 2022.7.2 and it works for me? I am running the x86_64 image (homeassistant/home-assistant:2022.7.2).

**Comment by acurrington** [comment]
I upgraded to 2022.7.2 and it seems to be working for me. Strange that 2022.7.1. also works for you but not for me. ¯\_(ツ)_/¯
