### ISSUE TITLE
New feature: Updates

### ISSUE THREAD

**Issue by boehser-enkel** [ualex73/monitor_docker#107]
Hi,

since portainer included update check of container images and webhook to rebuild them how about a update check & update function for container?

greetz

**Comment by loeffelpan** [comment]
Would love to see this feature.
SSHing with homeassistant to the host and sending docker commands to pull and compose is really ugly.

**Comment by derekoharrow** [comment]
Would be great to have this. I achieve this today using WhatsUpDocker which integrates with Home Assistant:

https://fmartinou.github.io/whats-up-docker/#/introduction/?id=good-integration-with

**Comment by derekoharrow** [comment]
> Thanks for your tip. How to integrate WUD to Home Assistent? Just RESTful sensor and Webhook triggers or am I missing something?

It's not very easy to find in the WhatsUpDocker documentation, but if you look [here](https://fmartinou.github.io/whats-up-docker/#/configuration/triggers/mqtt/) you can see that you can set it up to create MQTT sensors that Home Assistant auto-discovers.

**Comment by loeffelpan** [comment]
@derekoharror
Sorry for bothering you again.
I took a look at wud as an workaround.

But I don't get how to manually update containers with wud. Just trigger a webhook and update automatically seems to be possible.

**Comment by ualex73** [comment]
e.g. watchtower is a solution for this, so I will close this ticket.

**Comment by boehser-enkel** [comment]
> e.g. watchtower is a solution for this, so I will close this ticket.

It’s just a workaround

**Comment by ualex73** [comment]
If you are willing to create a PR, I am happy to review it.
