### ISSUE TITLE
Option to in/ex-clude containers for `switchenabled`

### ISSUE THREAD

**Issue by RoboMagus** [ualex73/monitor_docker#113]
There is a selection of containers that I'd like to be able to start / stop through HomeAssistant. To avoid the security hassle of potentially disabling critical containers it would be a great addition to allow a list of containers to include (or exclude) from getting a swicht instead of just the boolean option to generate switches for all containers based on `switchenabled`.

Perhaps this could be done by making the `switchenabled` parameter accept either a boolean or a dictionary of containers for which the fearure should be enabled?

If you're open to integrate this feature but unable to make time for it I might be able to look into it myself and open up a PR.

**Comment by hellcry37** [comment]
up

**Comment by RoboMagus** [comment]
Closing, as mentioned PR got merged.
