### ISSUE TITLE
Feature Request: allinone monitored condition for docker instances.

### ISSUE THREAD

**Issue by SlickUnderTheGun** [ualex73/monitor_docker#114]
I would like to be able to have one sensor per docker instance containing all or a subset of attributes for that instance, similar to the allinone container sensor. I monitor multiple docker instances and this would help keep the number of entities created in Home Assistant more organized.

**Comment by ualex73** [comment]
Sounds interesting, but it will get super complex to make this in the code. So the allinone option will still give you the least numbers of entities. I will close this ticket.
