### ISSUE TITLE
Small typo in the README.md file

### ISSUE THREAD

**Issue by IgalKolihman** [ualex73/monitor_docker#117]
There is a minor typo that is easy to fix. Just under [Monitor Docker](https://github.com/ualex73/monitor_docker#monitor-docker) heading, the second sentence.

It says: ` It can connected to the Docker...`

I believe that it should be: ` It can connect to the Docker...`

**Comment by ualex73** [comment]
Thanks for reporting it, I will fix in my next pull request of the README.
