### ISSUE TITLE
Feature request to add disk usage

### ISSUE THREAD

**Issue by erkr** [ualex73/monitor_docker#118]
Hi,
I would love to have disk usage added to the monitored_conditions. Especially useful for database add ons like InfluxDB.
I currently retrieve the size of the influx DB via an init command in The SSH & Web Terminal add-on: 
‘ docker exec addon_a0d7b954_influxdb du -s
    /data/influxdb/data/homeassistant | mosquitto_pub -t …’
(For more info See: https://community.home-assistant.io/t/unreliable-influxdb-size-sensor/226871/49)
So it would be great if similar disk usage sensors for particular folder (default root) inside the add ons could be created via this integration. Easier to set up and it would eliminate the need to publish them via MQTT

Best Eric

**Comment by erkr** [comment]
Thanks, that is indeed a feasible option. Thanks for the example!

**Comment by RoboMagus** [comment]
Happy to help.
After posting that sensor config I found out that depending on system load and directory size the time required to execute the command may exceed the default timeout. For that you may wish to increase the timeout if you run into that.
