### ISSUE TITLE
DockerError 900 - Cannot connect to Docker Engine via unix:///run/docker.sock 

### ISSUE THREAD

**Issue by ppastur** [ualex73/monitor_docker#123]
Hello, 

I have all my services running as containers including Portainer and Home Assistant.  Portainer connects fine via /var/run/docker.sock:/var/run/docker.sock.  I can't seem to get monitor_docker running using the same mapping.  The error I see in the HA logs is:

> 2023-04-27 12:14:43.514 ERROR (Thread-2 (RunDocker)) [custom_components.monitor_docker] Failed Docker connect: DockerError(900, 'Cannot connect to Docker Engine via unix:///run/docker.sock [Cannot connect to unix socket /run/docker.sock ssl:default [Permission denied]]')<

Here is my docker-compose file for HA (with some sensitive info removed)
>services:
  homeassistant:
    image: lscr.io/linuxserver/homeassistant:latest
    container_name: name
    hostname: hostname
    dns:
      - x.x.x.x
      - x.x.x.x
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Australia/Sydney
    volumes:
      - /share/path to homeassistant/homeassistant/config:/config
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - xxx3:xxx3 #optional
    restart: always
networks:
  default:
    external: false
    name: network_here<

May I ask for some help please - what am I doing wrong?

**Comment by PoetaGA** [comment]
In SSH or in Terminal, run this command "sudo chmod 664 /var/run/docker.sock"

After this, Home Assistant can access to Docker Sock

**Comment by B4dC4rd** [comment]
Hello @PoetaGA In my case, the command didn't help.

I first tried to run it in Home Assistant :-D but finally ran it in my NAS environement where the docker is hosted.

The command seemd to run without errors but no joy even after rebooting HASS.

Is there anything elese I could check ?

**Comment by B4dC4rd** [comment]
By the Way, Here is the result of thrying to run the command : docker -H tcp://**.**.**.**:2376 in my NAS via SSH.

Usage:  docker [OPTIONS] COMMAND

A self-sufficient runtime for containers

Options:
      --config string      Location of client config files (default
                           "/var/services/homes/**/.docker")
  -c, --context string     Name of the context to use to connect to the
                           daemon (overrides DOCKER_HOST env var and
                           default context set with "docker context use")
  -D, --debug              Enable debug mode
  -H, --host list          Daemon socket(s) to connect to (default )
  -l, --log-level string   Set the logging level
                           ("debug"|"info"|"warn"|"error"|"fatal")
                           (default "info")
      --tls                Use TLS; implied by --tlsverify
      --tlscacert string   Trust certs signed only by this CA (default
                           "/var/services/homes/**/.docker/ca.pem")
      --tlscert string     Path to TLS certificate file (default
                           "/var/services/homes/**/.docker/cert.pem")
      --tlskey string      Path to TLS key file (default
                           "/var/services/homes/**/.docker/key.pem")
      --tlsverify          Use TLS and verify the remote
  -v, --version            Print version information and quit

Management Commands:
  builder     Manage builds
  config      Manage Docker configs
  container   Manage containers
  context     Manage contexts
  image       Manage images
  manifest    Manage Docker image manifests and manifest lists
  network     Manage networks
  node        Manage Swarm nodes
  plugin      Manage plugins
  secret      Manage Docker secrets
  service     Manage services
  stack       Manage Docker stacks
  swarm       Manage Swarm
  system      Manage Docker
  trust       Manage trust on Docker images
  volume      Manage volumes

Commands:
  attach      Attach local standard input, output, and error streams to a runnin                                                                                                                                    g container
  build       Build an image from a Dockerfile
  commit      Create a new image from a container's changes
  cp          Copy files/folders between a container and the local filesystem
  create      Create a new container
  diff        Inspect changes to files or directories on a container's filesyste                                                                                                                                    m
  events      Get real time events from the server
  exec        Run a command in a running container
  export      Export a container's filesystem as a tar archive
  history     Show the history of an image
  images      List images
  import      Import the contents from a tarball to create a filesystem image
  info        Display system-wide information
  inspect     Return low-level information on Docker objects
  kill        Kill one or more running containers
  load        Load an image from a tar archive or STDIN
  login       Log in to a Docker registry
  logout      Log out from a Docker registry
  logs        Fetch the logs of a container
  pause       Pause all processes within one or more containers
  port        List port mappings or a specific mapping for the container
  ps          List containers
  pull        Pull an image or a repository from a registry
  push        Push an image or a repository to a registry
  rename      Rename a container
  restart     Restart one or more containers
  rm          Remove one or more containers
  rmi         Remove one or more images
  run         Run a command in a new container
  save        Save one or more images to a tar archive (streamed to STDOUT by de                                                                                                                                    fault)
  search      Search the Docker Hub for images
  start       Start one or more stopped containers
  stats       Display a live stream of container(s) resource usage statistics
  stop        Stop one or more running containers
  tag         Create a tag TARGET_IMAGE that refers to SOURCE_IMAGE
  top         Display the running processes of a container
  unpause     Unpause all processes within one or more containers
  update      Update configuration of one or more containers
  version     Show the Docker version information
  wait        Block until one or more containers stop, then print their exit cod                                                                                                                                    es

Run 'docker COMMAND --help' for more information on a command.

To get more help with docker, check out our guides at https://docs.docker.com/go                                                                                                                                    /guides/

**Comment by B4dC4rd** [comment]
> In SSH or in Terminal, run this command "sudo chmod 664 /var/run/docker.sock"
> 
> After this, Home Assistant can access to Docker Sock

Should this be run from a specific account? I've tried with the NAS Admin

**Comment by B4dC4rd** [comment]
Hi @ualex73 , do you have any clue on what the issue could be or what should I look at?

**Comment by B4dC4rd** [comment]
I also get this type or error, but the containers affected seem random:

[Docker] nw_cloudflare: Container not available anymore (3) (DockerError(900, 'Cannot connect to Docker Engine via tcp://redacted_IP:2375 [Server disconnected]'))

**Comment by B4dC4rd** [comment]
Still stuck :-( 
Hi @ualex73 do you have feedback to share on your side?
Cheers

**Comment by apedance** [comment]
I recently encountered the same error. Happened without any modification.
Only one machine affected.

**Comment by Alonzzzo2** [comment]
same here, Can't get this to work

**Comment by naimadfpv** [comment]
same here. cant connect to docker.

homeassistant is running on a raspi with hassos. 
192.168.178.5

docker is running on another host. 
192.168.178.19

**Comment by ualex73** [comment]
I updated the README.md with the comment of i4mr000t, so I will close this ticket.
