### ISSUE TITLE
Documentation improvement

### ISSUE THREAD

**Issue by turboc1208** [ualex73/monitor_docker#126]
I admit I'm somewhat dense sometimes.  But on the allinone sensor description, please add a note that any other sensors specified not be created if this is chosen.  The way I read it was that allinone would create one sensor with all sensors detailed under it.  I did not understand that it would exclude the individual sensors from being seen.  Personally I would like it if we could see both the individual sensors and the allinone for use on a rollup page and act on the other sensors in automations.

**Comment by ualex73** [comment]
I added the comment/note to the allinone ... but creating both types, that becomes a bit complex. Also, in general you only use the allinone or separate ones.
