### ISSUE TITLE
Container sensors not created if container depends on homeassistant

### ISSUE THREAD

**Issue by turboc1208** [ualex73/monitor_docker#127]
I run Appdaemon fairly heavily for my automations.  I run into problems when I restart HA if I don't restart Appdaemon afterwards.  So I thought I'll just make Appdaemon dependent on HA starting successfully.  That works great, but now none of the Appdaemon containers sensors are available in HA anymore.  It kind of makes sense when HA started it queried all the containers and built the correct entities and since AD wasn't running, it couldn't find any.  Can monitor_docker check back out ever so often for any containers it was told to monitor and couldn't find?  Maybe on a rolling time frame, 1 minute after startup for the first re-check, then 2 minutes later, then 4 minutes later, the 8 minutes later, then give up?  Something like that maybe??

**Comment by ualex73** [comment]
This still persists? Also, I do not understand the reproduction scenario yet?

**Comment by ualex73** [comment]
I will close this one, if it happens again, please raise a new issue.
