### ISSUE TITLE
Problem Getting Running

### ISSUE THREAD

**Issue by flannelman173** [ualex73/monitor_docker#13]
Hello. I am sure I am missing something simple, but following the steps leaves me with errors. I am running Hassio in a docker container. OS is Raspbian (RPi 4). From terminal I use the command:

`
sudo docker run -v /var/run/docker.sock homeassistant/home-assistant

`
This seems to go through the proper steps, but at the end I get this error:

"Unable to find configuration. Creating default one in /config" and the attempt errors out.

Any suggestions?

**Comment by ualex73** [comment]
The error comes from Home Assistant itself. I think you didn't follow the wiki:
https://www.home-assistant.io/docs/installation/docker/

For your setup, it needs to at bare minimum:
```
docker run -d -v /PATH_TO_YOUR_CONFIG:/config -v /var/run/docker.sock homeassistant/home-assistant
```

**Comment by flannelman173** [comment]
When I run the command you listed there, a new container is created with image "homeassistant/home-assistant". I do not think that is the intent because I am still getting the "Can not connect to Docker API (Missing valid docker_host.Either DOCKER_HOST or local sockets are not available.)" error in logs.

Sorry for confusion, I am not very familiar with Docker. Am I missing something?

**Comment by ualex73** [comment]
How are you starting/creating your HA at this moment? The integration assumes you know docker a bit.

**Comment by ualex73** [comment]
Closing this one, if you think it is a monitor_docker issue, please open a new issue with all relevant logging.
