### ISSUE TITLE
Problems with Docker in HomeAssistant Running in a VM

### ISSUE THREAD

**Issue by SvenMartin81** [ualex73/monitor_docker#133]
Hi,
I had a Long time docker_monitor sucessfully Running in HA as the HA was in an Docker Container. Since I Have HA in a VM (Virtual machine) there is nothing with Docker possible.

what ca I do. Is there any possible ?

**Comment by ualex73** [comment]
Did you manage to get it to work? There is some write-up in the README.

**Comment by ualex73** [comment]
I will close this one, if it happens again, please raise a new issue.
