### ISSUE TITLE
Possible to turn on/off group of containers based on a compose file ? 

### ISSUE THREAD

**Issue by amitn322** [ualex73/monitor_docker#135]
Is it possible to turn on/off a group of containers based on a docker-compose.yml ? 

For example if I have three dockers as a part of an application that are started/stopped by a single docker-compose.yml , can I make  a single switch to turn on/off or would it require separate switches ? 

Thank You,

**Comment by ualex73** [comment]
Not really, the information is not easily exposed and then still ... it becomes tricky, I would recommend you make it a separate trigger with multiple actions (e.g. 3 restarts, in the order you like).
