### ISSUE TITLE
No Entities appear

### ISSUE THREAD

**Issue by mjiines** [ualex73/monitor_docker#138]
I don't know if I just don't understand how or when this integration should be used, but my intent was the following:

Monitor the “Docker” Containers (Add-ons installed from HA). Nothing more.

As I was reading the Documentation, I came across the following explanation: 
When Home Assistant is used within a Docker container, the Docker daemon should be mounted as follows -v /var/run/docker.sock:/var/run/docker.sock.

My HA Instance in not within a Docker Container as far as I am aware. I don't see it in Portainer, and it wasn't the Docker Install Option when I set it up. It's a HA OS Machine run inside a proxmox vm. It's Set up the “usual way”, I'd never consciously install HA on docker for this reason, it always manages to generate big problems for no reason.

If I configure the integration the same as the example config, I only get this in the Logs:
[Docker]: Can not connect to Docker API (Missing valid docker-host. Either DOCKER_HOST or local sockets are not available.)

Every imaginable thing I've read about troubleshooting involves this thing: /var/run/docker.sock. So it seems every one except me runs HA in Docker for some reason.
But as I understand it that should only apply when HA was installed the “Docker way” not the standalone installation.

Maybe it isn't supposed to work this way, but I thought it “should” be able to monitor the other “real” docker container “add-ons” running on the System.

If for whatever reason I have to do the /var/run/docker.sock Thing as everyone else apparently, then can someone explain how I am even supposed to do that if Hass or Homeassistant isn't even listen in Portainer.

**Comment by ualex73** [comment]
What type of HA are you using? Docker? HAOS?

**Comment by ualex73** [comment]
I will close this one, if it happens again, please raise a new issue.
