### ISSUE TITLE
Container Running or not

### ISSUE THREAD

**Issue by nytram-md** [ualex73/monitor_docker#14]
Hi

Not sure if I have missed the variable but is there a way to see if the container is running or turned off rather than up 9 days for example. Id rather see running or off

I also have this notification but the switches that have been created all work OK 

![image](https://user-images.githubusercontent.com/55548608/86264365-53a73680-bbba-11ea-9885-fefcf24f5c4d.png)

Keep up the good work

Thanks

Martyn

**Comment by ualex73** [comment]
It exist, but it wasn't document (oeps!). Change "status" to "state" and you should be there.

Not sure what that type of error is, does the log say anything useful?

**Comment by ualex73** [comment]
I also updated the README file to reflect the "state" info ;-)

**Comment by nytram-md** [comment]
Hi

Thanks for that. appreciate it.

Ive just upgraded to v 0.112.0 and docker seems to have removed the /var/run/docker.sock:/var/run/docker.sock bind that I had this afternoon when it was all working. Do you want me to create a new issue and move or is it OK here ?

![image](https://user-images.githubusercontent.com/55548608/86296658-3b064300-bbf1-11ea-81c2-5c74b2c22224.png)

![image](https://user-images.githubusercontent.com/55548608/86296732-6b4de180-bbf1-11ea-83fe-4c3461efbe09.png)

**Comment by nytram-md** [comment]
re binded the /var/run/docker.sock in portainer and all working again but I now have the switch issue again

Can you see anything wrong with my code as nothing in the logs that I can see?

Thanks again

`monitor_docker:
  - name: Docker
    containers:
      - letsencrypt
      - docker_db_1
      - docker_ghost_1
      - docker_cloudflare-ddns_1
      - ha_dockermon
      - homeassistant
    rename:
      letsencrypt: Webserver
      docker_db_1: MYSQL
      docker_ghost_1: "Ghost Blogg"
      docker_cloudflare-ddns_1: "Cloudflare DNS" 
      ha_dockermon: "HA Docker Monitor"
      homeassistant: "Home Assistant"
    monitored_conditions:
      - version
      - containers_running
      - containers_stopped
      - containers_total
      - status
      - state
      - memory
      - uptime`

**Comment by nytram-md** [comment]
Just found this log which may help for the switch issue. Its happened in 0.111.4 and 0.112.0

`Log Details (ERROR)
Logger: homeassistant.components.rest.sensor
Source: components/rest/sensor.py:113
Integration: rest (documentation, issues)
First occurred: 0:00:33 (60 occurrences)
Last logged: 0:08:11

Error fetching data: http://192.168.0.11:8126/container/homeassistant failed with HTTPConnectionPool(host='192.168.0.11', port=8126): Max retries exceeded with url: /container/homeassistant (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f828d3db290>: Failed to establish a new connection: [Errno 111] Connection refused'))
Error fetching data: http://192.168.0.11:8126/container/docker_cloudflare-ddns_1 failed with HTTPConnectionPool(host='192.168.0.11', port=8126): Max retries exceeded with url: /container/docker_cloudflare-ddns_1 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f828d3ddad0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Error fetching data: http://192.168.0.11:8126/container/docker_ghost_1 failed with HTTPConnectionPool(host='192.168.0.11', port=8126): Max retries exceeded with url: /container/docker_ghost_1 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f8275feedd0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Error fetching data: http://192.168.0.11:8126/container/letsencrypt failed with HTTPConnectionPool(host='192.168.0.11', port=8126): Max retries exceeded with url: /container/letsencrypt (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f8275fee5d0>: Failed to establish a new connection: [Errno 111] Connection refused'))
Error fetching data: http://192.168.0.11:8126/container/docker_db_1 failed with HTTPConnectionPool(host='192.168.0.11', port=8126): Max retries exceeded with url: /container/docker_db_1 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f8275fec8d0>: Failed to establish a new connection: [Errno 111] Connection refused'))`

**Comment by ualex73** [comment]
> 
> 
> re binded the /var/run/docker.sock in portainer and all working again but I now have the switch issue again. Will I have to do this after every upgrade ?
> 
> Can you see anything wrong with my code as nothing in the logs that I can see?
> 
> Thanks again
> 
> `monitor_docker:
> 
>     * name: Docker
>       containers:
>       
>       * letsencrypt
>       * docker_db_1
>       * docker_ghost_1
>       * docker_cloudflare-ddns_1
>       * ha_dockermon
>       * homeassistant
>         rename:
>         letsencrypt: Webserver
>         docker_db_1: MYSQL
>         docker_ghost_1: "Ghost Blogg"
>         docker_cloudflare-ddns_1: "Cloudflare DNS"
>         ha_dockermon: "HA Docker Monitor"
>         homeassistant: "Home Assistant"
>         monitored_conditions:
>       * version
>       * containers_running
>       * containers_stopped
>       * containers_total
>       * status
>       * state
>       * memory
>       * uptime`

This is a Docker upgrade issue, it isn't a monitor_docker problem. I am not sure how you create a new Home Assistant container? I myself use docker-compose and then it is automatically picked up during each upgrade (cannot access my config, so i cannot copy-paste it).

**Comment by ualex73** [comment]
> 
> 
> Just found this log which may help for the switch issue. Its happened in 0.111.4 and 0.112.0
> 
> `Log Details (ERROR)
> Logger: homeassistant.components.rest.sensor
> Source: components/rest/sensor.py:113
> Integration: rest (documentation, issues)
> First occurred: 0:00:33 (60 occurrences)
> Last logged: 0:08:11
> 
> Error fetching data: http://192.168.0.11:8126/container/homeassistant failed with HTTPConnectionPool(host='192.168.0.11', port=8126): Max retries exceeded with url: /container/homeassistant (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f828d3db290>: Failed to establish a new connection: [Errno 111] Connection refused'))
> Error fetching data: http://192.168.0.11:8126/container/docker_cloudflare-ddns_1 failed with HTTPConnectionPool(host='192.168.0.11', port=8126): Max retries exceeded with url: /container/docker_cloudflare-ddns_1 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f828d3ddad0>: Failed to establish a new connection: [Errno 111] Connection refused'))
> Error fetching data: http://192.168.0.11:8126/container/docker_ghost_1 failed with HTTPConnectionPool(host='192.168.0.11', port=8126): Max retries exceeded with url: /container/docker_ghost_1 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f8275feedd0>: Failed to establish a new connection: [Errno 111] Connection refused'))
> Error fetching data: http://192.168.0.11:8126/container/letsencrypt failed with HTTPConnectionPool(host='192.168.0.11', port=8126): Max retries exceeded with url: /container/letsencrypt (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f8275fee5d0>: Failed to establish a new connection: [Errno 111] Connection refused'))
> Error fetching data: http://192.168.0.11:8126/container/docker_db_1 failed with HTTPConnectionPool(host='192.168.0.11', port=8126): Max retries exceeded with url: /container/docker_db_1 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f8275fec8d0>: Failed to establish a new connection: [Errno 111] Connection refused'))`

Hmmm... according to the error, it cannot connect to the TCP of the remote docker host (connection refused). In such case switches and sensors both shouldn't work. That connection refused you need to solve first, before you continue with monitor_docker.

**Comment by nytram-md** [comment]
Hi

No problems if I just need to add the mount now I know.

Does the log help for the switches issue ?

Martyn


Regards

Martyn

________________________________

**Comment by nytram-md** [comment]
The switches work though. I turned off a container last night as i originally used phil Hawthornes HA Docker Mon, so had a container I could turn off. I liked yours more as it was in HACS and had more sensors.
[Image]




Regards

Martyn

________________________________

**Comment by ualex73** [comment]
I can't see the issue with the switches at this moment?

**Comment by malinduta** [comment]
Same issue here regarding the switches.
Working to start/stop containers, but throws error when starting HA.

**Comment by ualex73** [comment]
@malinduta please open a new issue and please include error and possible debug logging, without it, I can't do much with it.

**Comment by ualex73** [comment]
@nytram-md in version 1.2 the switch error is solved (was a strange reason, not related to the code)
