### ISSUE TITLE
all entities disappeared following update to 1.17

### ISSUE THREAD

**Issue by wildenrou** [ualex73/monitor_docker#149]
Hi, first thanks for this extermely useful HASS component. I updated to 1.17 and restarted my hass instance and since then, all home assistant entities that were initially generated by the tool are gone. Would you know why?
Thanks in advance!

**Comment by wildenrou** [comment]
I fixed this by listing all monitored conditions as it seems to be not defaulting to all anymore (as discussed in isssue #143 ). Thanks

**Comment by bobbinz** [comment]
Issue 148 is resolved :)

**Comment by ualex73** [comment]
@wildenrou it was a bug, fixed in the latest version.

**Comment by wildenrou** [comment]
thanks!
