### ISSUE TITLE
Issue after upgrading to Home Assistant 2024.10.1

### ISSUE THREAD

**Issue by Caros2017** [ualex73/monitor_docker#163]
After upgrading to Home Assistant 2024.10.1 I am getting the following message:

`Setup failed for custom integration 'monitor_docker': Requirements for monitor_docker not found: ['python-dateutil==2.9.0', 'aiodocker==0.22.0'].`

After downgrading to HA 2024.9.x it's working fine again.

**Comment by ualex73** [comment]
I tried it with 2024.10.1 too, but it works here?

**Comment by Caros2017** [comment]
> I tried it with 2024.10.1 too, but it works here?

Thanks for your reply. Now I know I had to find it somewhere else. I am running HA with restricted policies. This was my solution:
[Link](https://github.com/tribut/homeassistant-docker-venv/blob/master/run)

Your plugin is working fine now.
