### ISSUE TITLE
wrong image count

### ISSUE THREAD

**Issue by PD75** [ualex73/monitor_docker#21]
sensor.docker_images | 23 | friendly_name: Docker Images icon: mdi:docker
-- | -- | --
I have 9 images, not 23....

![image](https://user-images.githubusercontent.com/10294795/87472285-faaaba00-c61f-11ea-8085-919c67751824.png)

**Comment by ualex73** [comment]
I get the sensor information from the Docker API directly, it is equal to:
docker images -a

I think your docker images results 9 and docker images -a returns 23.

The API has no other quick/simple way of filtering out the intermediate images.

**Comment by ualex73** [comment]
Currently it works as-is, i am happy to accept a PR.

**Comment by PD75** [comment]
Hmm, I see what you mean. I will investigate and see if it is something I can do. Will closer this in the mean time.
