### ISSUE TITLE
monitored_condition allinone not working.

### ISSUE THREAD

**Issue by PD75** [ualex73/monitor_docker#22]
![image](https://user-images.githubusercontent.com/10294795/87472547-61c86e80-c620-11ea-95dc-1954f250e34c.png)

**Comment by ualex73** [comment]
Are you using the HACS version or the downloaded version from github? The HACS version doesn't have this feature yet (i will release that part in the next few days)

**Comment by PD75** [comment]
@ualex73 HACS...

**Comment by ualex73** [comment]
Just released a new version 1.2, should be available in HACS in 5-6 hours.

**Comment by ualex73** [comment]
version 1.3 is also out, so we can close this one now.
