### ISSUE TITLE
Some monitored conditions work as sensors, but not as attributes

### ISSUE THREAD

**Issue by LordShadowen** [ualex73/monitor_docker#24]
I was experimenting with allinone, and discovered that some conditions that work fine as sensors, report "null" when set as attributes. I didn't try them all, but so far:
cpu_percentage
network_speed_up
network_speed_down

These do work:
memory_percentage
image
status

As a side note, why not make "allinone" a main configuration parameter instead of a "fake" monitored condition? Not only is not very intuitive, it has the downside of forcing the manual selection of every condition. When the list of empty, we get all (great!), but as soon as allinone is added, we get no attributes on the sensors and every single monitored condition needs to be included manually.

**Comment by ualex73** [comment]
Ok, this is a bug ... i just committed a fix for it. Also if only "allinone" is configured, it will default to all sensors.

I thought putting "allinone" as a separate option, but that would add more configuration - that's the main reason why i did it that way (and it should be documented enough i hope?)

**Comment by LordShadowen** [comment]
ok, seems to be working now :)

**Comment by ualex73** [comment]
OK, then we can close this one ;-)
