### ISSUE TITLE
Error handling changes to the list of containers

### ISSUE THREAD

**Issue by LordShadowen** [ualex73/monitor_docker#25]
If the allinone contion is active and then there's a change to the list of containers in docker itself (adding one, removing one, etc...) the integration rebuilds all the sensors as separate entities instead of keeping them as one sensor per container.  
Restarting HA reverts everything back to normal.

**Comment by ualex73** [comment]
Ok, i didn't explicitly test that scenario. I will do that somewhere next week and then i will try to fix it.

**Comment by ualex73** [comment]
Should be fixed in the latest commit, but not available via HACS.

**Comment by ualex73** [comment]
@LordShadowen you got time to test it?

**Comment by LordShadowen** [comment]
Yes - I did. Yep, seems to work fine now

**Comment by ualex73** [comment]
Cool, then we can close this one ;-)
