### ISSUE TITLE
DOCKER_TLS_VERIFY & ...CERT_PATH where to set the env. vars?

### ISSUE THREAD

**Issue by mwunderling** [ualex73/monitor_docker#27]
This question is related to Q's 4&5 in the Q&A section

I am able to connect this component to the same Docker instance home assistant is running in but I also have a 2nd Docker instance running on a separate NAS box that I would like it to connect to. Per Q4, I see the docker_tls_verify & docker_cert_path environment variables need to be set, but where?

**Comment by ualex73** [comment]
I added a docker-compose example to the Q&A 4, does this answer your question?

**Comment by mwunderling** [comment]
LOL, yes, pretty sure. Will give a try a little later. 

Looks like I just about had it, Forgot to add the cert volume path in compose for HA. Had already tried with the env vars there but wasn't convinced that was the proper location for them... thus the question. Thanks!
