### ISSUE TITLE
How to use on Hass.IO

### ISSUE THREAD

**Issue by jon6fingrs** [ualex73/monitor_docker#28]
Hi, this isn’t a bug but wasn’t sure how else to send this information. I found this container: 

https://github.com/Tecnativa/docker-socket-proxy

I installed it on hass.io using the terminal and was then able to connect to it using docker monitor. Working great and thought I’d share. Thanks!

**Comment by ualex73** [comment]
Thanks for testing & reporting it, I will add it to the Q&A section of the README for other hass.io users.

**Comment by ualex73** [comment]
It is added to the Q&A, so i can close this one.
