### ISSUE TITLE
Getting 2 different CPU readings?

### ISSUE THREAD

**Issue by CorneliousJD** [ualex73/monitor_docker#29]
I'm running on a server with 32 cores, but I'm seeing "Docker CPU" and "Docker 1CPU"

This is also showing on each sensor for each container when running in "allinone" mode.
I'm not sure what the difference is, but they're displaying two different values.

PS - When running on unRAID and HomeAssistant Core is running as a container on unRAID, you need to add a new path, very simple to do, but may want to add it to your readme for users who are on unraid and not familair with exec/compose.

Here's a screenshot if you decide to add the info.

![image](https://user-images.githubusercontent.com/724777/89226928-c8e79c00-d5aa-11ea-96e0-19d7d7976e42.png)

**Comment by CorneliousJD** [comment]
Here's an example of CPU and 1CPU -- forgot to include screenshot of that.

![image](https://user-images.githubusercontent.com/724777/89227010-ef0d3c00-d5aa-11ea-8c22-39bcd8ac750c.png)

**Comment by ualex73** [comment]
The difference between cpu and 1cpu is maybe not clear on the page, but it works as follows:
The "cpu" can show a value between 0 and 3200% (if you got 32 cores * 100)
The "1cpu" can only show 0-100%. So it divide the "cpu" by the number of cores

I will add the UnRAID example/screenshot to the Q&A soon.

**Comment by CorneliousJD** [comment]
Thanks for the info - I understand the difference now - makes sense :) 

Thanks for making this - I was STILL using HADockermon for such a long time but this is just so much better and doesn't need another container to work, much better. 

Thanks agian.
