### ISSUE TITLE
Think I miss something

### ISSUE THREAD

**Issue by MYLE-01** [ualex73/monitor_docker#3]
in my logs i have

```
2020-06-16 11:21:59 ERROR (Thread-8) [custom_components.monitor_docker.helpers] Can not connect to Docker API (Missing valid docker_host.Either DOCKER_HOST or local sockets are not available.)
```

**Comment by ualex73** [comment]
Can you share your configuration.yaml?

**Comment by ualex73** [comment]
To test the URL, can you add to your section:
url: unix:///var/run/docker.sock

Note the 3 "/" please.

**Comment by to4ko** [comment]
> url: unix:///var/run/docker.sock

how this can be done in case of supervised installation on generic linux?

**Comment by ualex73** [comment]
Sorry, I have no knowledge how the supervised installation works with Docker.

**Comment by to4ko** [comment]
ah...ok.removed

**Comment by ualex73** [comment]
@MYLE-01 Is it still a problem? Otherwise lets close this issue ticket.
