### ISSUE TITLE
Feature: Add exclude docker option

### ISSUE THREAD

**Issue by juan11perez** [ualex73/monitor_docker#30]
First thank you for producing and sharing this component.
Please consider adding the exclude option.
Use case: running 40+ dockers and excluding a few, rather than listing all,  would be a welcome approach.

**Comment by ualex73** [comment]
This should be possible, i will have a look into it.

**Comment by juan11perez** [comment]
Thank you for considering it.Sent from my Samsung Galaxy smartphone.
-------- Original message --------From: Alexander <notifications@github.com> Date: 10/08/2020  15:09  (GMT+04:00) To: ualex73/monitor_docker <monitor_docker@noreply.github.com> Cc: juan11perez <juan11perez@yahoo.com>, Author <author@noreply.github.com> Subject: Re: [ualex73/monitor_docker] Feature: Add exclude docker option (#30) 
This should be possible, i will have a look into it.
