### ISSUE TITLE
Feature: Check if a newer latest image is available

### ISSUE THREAD

**Issue by Burningstone91** [ualex73/monitor_docker#37]
Hi,

I wrote a small script to check if there is a newer version available of the currently used image. See [this](https://community.home-assistant.io/t/system-monitoring-how-does-your-look/109713/666) post on the HA forum. Someone suggested to open a feature request to get this added to your custom component. What's your opinion on that? Happy to help where I can.

**Comment by ualex73** [comment]
I checked your script, but it only works on the "latest" version I think? That makes it a bit not very generic solution. I couldn't think of one either, otherwise I would have implemented something already. At this moment watchtower or newreleases.io is a better approach.

**Comment by Burningstone91** [comment]
Yeah, that's the problem. And it also doesn't work for all images :(
I got it working for my needs, but hope you'll find a better solution at one point :)
What I don't like about watchtower that it downloads the image anyway, even if you don't want to update, right? Need to check out newreleases.io. 

I got it working for my needs, but hope you'll find a better solution at one point :)

**Comment by andreasbrett** [comment]
I go with [Diun](https://github.com/crazy-max/diun/) for monitoring updates. Has quite a few notification options (MQTT, webhooks, pushover etc) to integrate well into Home Assistant as well as directly notifying.

**Comment by ualex73** [comment]
I added the information to the readme, so I will close this one.
