### ISSUE TITLE
Permission denied with home assistant that is not a Docker

### ISSUE THREAD

**Issue by leranp** [ualex73/monitor_docker#40]
aiodocker.exceptions.DockerError: DockerError(900, 'Cannot connect to Docker Engine via unix:///run/docker.sock [Permission denied]')

the home assistant is in virtual environment ,tried to add homeassistant user to ducker group , tried to change the location of the docker.sock to unix:///run/docker.sock,
not luck, can someone help me?

**Comment by ualex73** [comment]
Strange, adding your user to "docker" group should have worked. You logout/login (or even reboot), before you tried?

```
usermod -a -G docker <user>
reboot
```
That should really do it

**Comment by leranp** [comment]
Thanks, reboot did the work
