### ISSUE TITLE
Some containers missing

### ISSUE THREAD

**Issue by derekoharrow** [ualex73/monitor_docker#42]
I have this setup to monitor all containers, and largely this is working, but it's missing a few containers.

I have about 28 containers, and 26 are perfectly visible. 2 don't appear.

Coincidentally, for both of these missing containers, there are other similarly named containers, so I suspect it's picking up one and not the other - e.g.

Found:

- wireguard-server

- plex

Missing

- wireguard

- plex-server

Any thoughts?

**Comment by ualex73** [comment]
This issue still persists?

**Comment by stnokott** [comment]
@theautomation please close this issue if it is resolved.
