### ISSUE TITLE
CPU percentage is higher than 100%

### ISSUE THREAD

**Issue by leranp** [ualex73/monitor_docker#43]
All my containers have a value of more then 100% , and the main CPU sensor is also more then 100 
It is normal?

**Comment by ildar170975** [comment]
I have to confirm the same bug - sometimes CPU percentage is > 100%.

**Comment by rAdziuB** [comment]
I have the same issue. Sometimes I have almost 300%. I use Docker on QNAP TS-453Be

**Comment by ualex73** [comment]
If you use "cpu_percentage" it is the CPU usage across all CPUs. So if you have 4 cores, the maximum CPU would be 400%. If you would have 8, then then maximum would be 800%.
Use "1cpu_percentage" to get it between 0-100% ... I will update the readme with this information for clarity.

**Comment by rAdziuB** [comment]
Ok, thanks. Now everything is clear.
