### ISSUE TITLE
Feature: Version of running container or also image in registry

### ISSUE THREAD

**Issue by spudje** [ualex73/monitor_docker#5]
Saw this coming by in HACS. Sounds interesting. This is a question (or feature request :) ) What I couldn't retrieve from the info is, does this also show the latest version of the image available on the registry, and optionally mark the running container as being out of date?

I don't want to run Watchtower or similar, just want a notification that a newer version of images is received.

**Comment by ualex73** [comment]
That wasn't the goal of this custom component, but i will have a look what i can do (something similar is on my wish list, most likely it would be a separate custom component).

**Comment by spudje** [comment]
Thanks for the quick reply! Don't feel obliged to add this. There are different ways to achieve this as well, e.g. newreleases.io. I'll figure something out.

**Comment by ualex73** [comment]
Thanks, i wasn't aware of the newreleases.io. That one seems to be easier to use, because it already interfaces to hub.docker.com ;-)

**Comment by ualex73** [comment]
I checked the docker api and the aiodocker I used, but this can't be (easily) implemented.

**Comment by colemamd** [comment]
There's already a built-in sensor for this. https://www.home-assistant.io/integrations/version/
