### ISSUE TITLE
helpers.py - SyntaxWarning: "is not" with a literal.

### ISSUE THREAD

**Issue by hllhll** [ualex73/monitor_docker#50]
Hi
Just now trying to install via HACS, got this error on boot
```
home-assistant   | /config/custom_components/monitor_docker/helpers.py:407: SyntaxWarning: "is not" with a literal. Did you mean "!="?
home-assistant   |   and self._info[ATTR_MEMORY_LIMIT] is not 0
```

**Comment by hllhll** [comment]
But everything works a-ok as it seems, just a warning

**Comment by ualex73** [comment]
Which python version are you using?

**Comment by ualex73** [comment]
Ok, see it on latest 3.8.6, fixed in the repo now

**Comment by ualex73** [comment]
I will close this one, the fix is in the repo. I will release a new version soon.
