### ISSUE TITLE
no values for memory

### ISSUE THREAD

**Issue by joostvanmourik** [ualex73/monitor_docker#53]
Implemented your component today got everything working after some time :-) but memory values are empty. Any idea how to solve this ?

**Comment by ualex73** [comment]
@joostvanmourik  are you running on a Raspberry Pi?

If you do, a fix can be found in the following link:
https://github.com/ualex73/monitor_docker/issues/26#issuecomment-723016034

(i will add this to the GitHub page)

**Comment by ualex73** [comment]
No further comment, I assume it is fixed now.
