### ISSUE TITLE
Please add version to manifest.json

### ISSUE THREAD

**Issue by firstof9** [ualex73/monitor_docker#56]
New requirements for custom components.

`2021-03-01 12:28:29 WARNING (MainThread) [homeassistant.loader] No 'version' key in the manifest file for custom integration 'monitor_docker'. This will not be allowed in a future version of Home Assistant. Please report this to the maintainer of 'monitor_docker'`

**Comment by ualex73** [comment]
Thanks for reporting it (i didn't run the dev/beta yet ;-)), i released this in v1.8. Should hit HACS in a few hours.
