### ISSUE TITLE
Can only restart container if container list explicitly specified

### ISSUE THREAD

**Issue by derekoharrow** [ualex73/monitor_docker#58]
I can use the restart service no problem if the container is specifically listed in the containers section in configuration.yaml.

However, the default for monitor_docker is to monitor all containers if you don't specify a list.

If you use the default, to monitor all containers, and don't specify a list, then the restart service doesn't work. It complains, for example:

`[custom_components.monitor_docker.switch] Service restart failed, container 'zigbee2mqtt' is not configured`

The desired behaviour would be to enable you to restart a service even if you used the default option and didn't list each docker container individually in the configuration.

**Comment by ualex73** [comment]
Thanks for the bug report, it should be fixed in the GitHub version. Can you test it out? If it works fine, I will push it via HACS.

**Comment by ualex73** [comment]
Version 1.9 has been released, so we can close this one.
