### ISSUE TITLE
monitor_docker disconnects from remote docker proxy after a while

### ISSUE THREAD

**Issue by hvalev** [ualex73/monitor_docker#63]
I'm using docker_monitor, where I'm registering a local docker monitor and a remote one (on the same subnet). I have noticed that starting/stopping docker containers on the remote stops working after a while, while locally everything works perfectly. I can confirm that the docker-socket-proxy (https://github.com/Tecnativa/docker-socket-proxy) is still running on the remote and the problem is not there. Perhaps due to a temporary loss of connectivity the tcp connection is lost and the tcp protocol does not automatically reestablish it. Do you have an idea?

**Comment by IDmedia** [comment]
I had the same problem and had to increase `scan_interval` to a value greater then 30. After that the connection was stable

**Comment by ualex73** [comment]
I will close this old issue. If still persists, please open a new issue.
