### ISSUE TITLE
Feature: Add exclude docker option

### ISSUE THREAD

**Issue by fatuuse** [ualex73/monitor_docker#65]
Nice to have exclusion setting, to exclude specific containers instead of lists monitored.

**Comment by fatuuse** [comment]
#30

**Comment by ualex73** [comment]
Can you try out v1.13-beta1 (https://github.com/ualex73/monitor_docker/releases/tag/1.13-beta1) and let me know if works for you?

next to the option "containers", there is now a "containers_exclude" option added.

**Comment by fatuuse** [comment]
Great!
