### ISSUE TITLE
Containers not defaulting to all

### ISSUE THREAD

**Issue by monotonus** [ualex73/monitor_docker#7]
Maybe I'm missing something, but I was not able to get all containers monitored. I tried with and without the "containers:" line, but both didn't work.

**Comment by juan11perez** [comment]
I can report the same. Only if I specify the container it will appear

**Comment by ualex73** [comment]
I think I see the problem, i will fix it tonight and push a new version.

**Comment by ualex73** [comment]
Ok, found it quickly. I just pushed a fix for it (updated sensor.py and switch.py). Tonight i will make it a new release.

**Comment by ualex73** [comment]
It is fixed in release 0.8, and 1.0 is out also (fixing some issues around (re-)creation of containers). If you find more issues, please let me know!

**Comment by juan11perez** [comment]
thank you for fixing and sharing this
