### ISSUE TITLE
feature request - add a containers exclude list 

### ISSUE THREAD

**Issue by anubisg1** [ualex73/monitor_docker#70]
The following configuration allows for "containers" to list all containers we want to monitor.

Please add an exclude list so that instead we list only what containers we do not want to monitor

**Comment by ualex73** [comment]
Please test v1.13-beta2, it has the "containers_exclude" option added.

**Comment by anubisg1** [comment]
Thank you, I'll test it

**Comment by ualex73** [comment]
I will close this one, please open a new ticket if it is does not work.
