### ISSUE TITLE
Add device registry info

### ISSUE THREAD

**Issue by escoand** [ualex73/monitor_docker#72]
I would like to request device registry info: https://developers.home-assistant.io/docs/device_registry_index/
As this integration provides quite much information this would simplify the overview in HA.

**Comment by schmittey** [comment]
Please correct me if I'm wrong, guess that's a duplicate to [ Request: unique_id registry for entities, to allow giving sensors an Area and UI customization #62 ](https://github.com/ualex73/monitor_docker/issues/62l) ?

**Comment by RoboMagus** [comment]
AFAIK, unique_id is required for the device info to work.

I've briefly looked into adding both to this component, but it would require a different setup procedure and with that quite a bit of refactoring.

**Comment by ualex73** [comment]
This is not possible, due to the nature of the integration. I added it to the Q&A section. I will close this ticket.
