### ISSUE TITLE
A few questions

### ISSUE THREAD

**Issue by TheDarthFather** [ualex73/monitor_docker#73]
First .. this is amazing! Easy to setup and use :) 
Big Thank you!

I do have 2 questions:
1. Is the state bugged ? I have a container that is stopped and the state shows Running, while the status is Exited ... (img below)
2. I woudl like to connect to another docker instance, and I see the setup in config .. seems easy .. but what do I need to do on the other machine to allow the connection ? Any guide / what to look for ?

https://imgur.com/kLMkOV1

**Comment by ualex73** [comment]
Any update on this one? otherwise lets close it.

**Comment by TheDarthFather** [comment]
Yes, I belive this came from the fact I used a button-card and when clicking on it "kind of" ruined something ... isn't that state read-only ?
