### ISSUE TITLE
In order to stop containers using the proxy container, you need to enable "POST" access in ENV

### ISSUE THREAD

**Issue by L44RS** [ualex73/monitor_docker#75]
Like the title says, in order to be able to stop/start containers using the Home Assistant switches, you need to grant the proxy container access to the POST parts of the API. This is done by setting auth to 1 in the env variables. This isn't mentioned in the docs, took me quite a lot of searching. Would be nice if this could be added.

**Comment by ualex73** [comment]
It is added, so I will close this one
