### ISSUE TITLE
Home assistant log error

### ISSUE THREAD

**Issue by legolas0802** [ualex73/monitor_docker#76]
I am on home assistant supervisor and I use the proxy container as per instructions, in the log I find the following error:

```Logger: custom_components.monitor_docker.helpers
Source: custom_components/monitor_docker/helpers.py:268
Integration: Monitor Docker (documentation, issues)
First occurred: 17:51:55 (1 occurrences)
Last logged: 17:51:55

[Docker]: run_docker_events loop ended 

Logger: homeassistant.components.sensor
Source: helpers/entity_platform.py:586
Integration: Sensore (documentation, issues)
First occurred: 18:02:11 (7 occurrences)
Last logged: 18:02:11

Entity id already exists - ignoring: sensor.docker_containers_total
Entity id already exists - ignoring: sensor.docker_containers_stopped
Entity id already exists - ignoring: sensor.docker_1cpu
Entity id already exists - ignoring: sensor.docker_memory
Entity id already exists - ignoring: sensor.docker_images
```
with the consequence that those entities disappear for all containers, to see them reappear after a few minutes. All in an infinite cycle.

**Comment by ualex73** [comment]
Does it happen every 10 minutes? It is possible the proxy container closes that connection every 10 minutes ... is that something you can check? I myself I am not using the proxy container and it looks like you are the first seeing this problem.

**Comment by legolas0802** [comment]
I check and let you know, but if the container closes the connection, shouldn't all the entities disappear? general docker information and switches remain there and are fully functional

**Comment by legolas0802** [comment]
i checked and it happens every 10 minutes

**Comment by ualex73** [comment]
Ok, confirmed:
https://github.com/Tecnativa/docker-socket-proxy/blob/master/haproxy.cfg

It has:
    timeout client 10m
    timeout server 10m

Your connection which closes, is the docker event thread ... so it only gets traffic when a container stops, starts, etc

You can download the haproxy.cfg from the GitHub link (above), modify it (e.g. 10min to 60min), and mount it inside the container.

**Comment by ualex73** [comment]
Other option could be:
configure a container with "health" check, this should generate event traffic. I cannot do this from monitor_docker.

**Comment by legolas0802** [comment]
I tried to increase the container time to 60 minutes, for both the client and the server. The problem is only postponed

**Comment by legolas0802** [comment]
I did another test, deleting the entries:
` timeout client 10m
  timeout server 10m`
the problem no longer arises.

**Comment by ualex73** [comment]
I am not sure you do not get any "docker events", because those should keep the connection open (aka alive). But thanks for further testing, I will add your fix to the README.

**Comment by clipse2004** [comment]
sorry if the question is rather stupid, but I have the same problem. 
however, my docker knowledge is quite poor, can I edit the haproxy via portainer? 
if not, can you help me how to get these two lines out? 

Thanks a lot!

**Comment by legolas0802** [comment]
> scusate se la domanda è un po' stupida, ma ho lo stesso problema. tuttavia, la mia conoscenza della finestra mobile è piuttosto scarsa, posso modificare l'haproxy tramite portainer? se no, puoi aiutarmi come ottenere queste due righe?
> 
> Molte grazie!

through portainer enter the console of the proxi container in / bin / sh mode, move to the path usr / local / etc / haproxy / haproxy.cfg and with the command "vi" edit the file

**Comment by tangweiji** [comment]
> > scusate se la domanda è un po' Stupida, ma ho lo stesso Problema. tuttavia，la mia conoscenza della Finestra mobile è piuttosto carsa，posso modificare l'haproxy tramite porttainer？不，你有什么需要注意的吗？
> > 莫尔特感恩！
> 
> 通过portainer以/bin/sh模式进入proxi容器的控制台，移动到路径usr/local/etc/haproxy/haproxy.cfg并使用命令“vi”编辑该文件


very useful

**Comment by ualex73** [comment]
I will close this old issue. If still persists, please open a new issue.
