### ISSUE TITLE
Configuring Monitor_docker Docker daemon

### ISSUE THREAD

**Issue by icornish72** [ualex73/monitor_docker#77]
Forgive my lack of competence on docker (This is new to me and I am learning...)
I run Home Assistant on a ProxMox Server - its running in a dedicated VM.
How can I mount the Docker daemon?

"If applicable, add the volume /var/run/docker.sock to your Home Assistant container."

It seems Portainer is no longer available, so can't use that anymore.

**Comment by icornish72** [comment]
**Note, I'm running HASSOS on Proxmox.

**Comment by ualex73** [comment]
Then you should look in the Q&A: "Question: Does this integration work with the HASS or supervisord installers?" ... that should work for you, you need to start another container (I don't run HASSOS myself - so this information is supplied by other users)

**Comment by ualex73** [comment]
It is described in the Q&A, so closing this one.
