### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'find'


### ISSUE THREAD

**Issue by b10126** [ualex73/monitor_docker#79]
Hi everyone,

The container are based on QNAP Containerstation and the implementation worked fine w/o problems. Since a few weeks I get the following error log in HA. 

Any suggestions what's going on?

Thanks in advance.

Logger: custom_components.monitor_docker.helpers
Source: custom_components/monitor_docker/helpers.py:118
Integration: Monitor Docker (documentation, issues)
First occurred: 08:20:17 (1 occurrences)
Last logged: 08:20:17

[Docker]: Can not connect to Docker API ('NoneType' object has no attribute 'find')
Traceback (most recent call last):
  File "/config/custom_components/monitor_docker/helpers.py", line 118, in __init__
    if startCount > 0 and url.find("unix:") != 0:
AttributeError: 'NoneType' object has no attribute 'find'

**Comment by b10126** [comment]
Additionally I've the following error log entry.

Dieser Fehler wurde von einer benutzerdefinierten Integration verursacht

Logger: custom_components.monitor_docker
Source: custom_components/monitor_docker/__init__.py:118
Integration: Monitor Docker (documentation, issues)
First occurred: 08:19:17 (1 occurrences)
Last logged: 08:19:17

invalid literal for int() with base 10: '7-qnap3'

**Comment by ualex73** [comment]
Can you try the latest 1.12-beta pre-release or download __init__.py and helpers.py and see if it solves the issue?

**Comment by lukaszzyla** [comment]
same problem here.
tested with 1.12beta - doesnt solve this issue...
2021-11-21 23:27:28 ERROR (Thread-3) [custom_components.docker_monitor] invalid literal for int() with base 10: '7-qnap3'

**Comment by b10126** [comment]
I also tried, but didn't solve the problem. Do you need some more information, logs or anything?

**Comment by ualex73** [comment]
Can you try 1.12-beta2 (https://github.com/ualex73/monitor_docker/releases/tag/1.12-beta2)? This should resolve the issue.

**Comment by b10126** [comment]
perfect work, it does work!
thanks a lot for your analysis and solving this problem.
