### ISSUE TITLE
Can no longer access docker containers after QNAP firmware update

### ISSUE THREAD

**Issue by mwunderling** [ualex73/monitor_docker#80]
Context:
Am running HA in Docker on a QNAP NAS. QNAP recently released a new numbered "5.xx" version of their QTS firmware. Prior was QTS 4.xx. Monitor_docker always connected to my docker containers under QTS 4.xx, but can't since updating the NAS to QTS 5.xx.

Log Errors:
I see two monitor_docker related errors when starting HA:

"ERROR (Thread-3) [custom_components.monitor_docker] invalid literal for int() with base 10: '7-qnap3'"

& 

ERROR (Thread-3) [custom_components.monitor_docker.helpers] [Docker]: Can not connect to Docker API ('NoneType' object has no attribute 'find')
Traceback (most recent call last):
  File "/config/custom_components/monitor_docker/helpers.py", line 118, in __init__
    if startCount > 0 and url.find("unix:") != 0:
AttributeError: 'NoneType' object has no attribute 'find'

The QNAP firmware update obviously changed something...but hoping there is a work around perhaps in the monitor_docker python?

**Comment by vibi75** [comment]
Same issue :(

**Comment by ualex73** [comment]
Sorry, I am unable to reproduce the problem here. I need more information/logging/etc to say more (especially it worked on QNAP 4.x and not anymore in 5.x does not help - maybe they changed the Docker API).

**Comment by mwunderling** [comment]
I left 2 related log error entries in my initial ticket. Your comments suggest you did not read those? ....or are you saying that is not enough? It seems @vibi75 spotted a related issue or the same in issue #78. This is the same log error I have listed above.

Obviously you can't fix something QNAP did, Hoping there is a workaround to their roadblock.

**Comment by willheineman** [comment]
Same issue on my QNAP TS-451+

**Comment by ualex73** [comment]
Can you try 1.12-beta2 (https://github.com/ualex73/monitor_docker/releases/tag/1.12-beta2)? This should resolve the issue.

**Comment by vibi75** [comment]
> Can you try 1.12-beta2 (https://github.com/ualex73/monitor_docker/releases/tag/1.12-beta2)? This should resolve the issue.

This, it works, thanks a lot @ualex73 !

**Comment by rAdziuB** [comment]
Hi, I also can confirm. Right now it seems to work fine on QTS 5.xx. Thanks, ualeX73!

**Comment by mwunderling** [comment]
Indeed, working now. Huge thanks!!!

**Comment by willheineman** [comment]
Thanks. That fixed it
