### ISSUE TITLE
Loosing connection via docker proxy

### ISSUE THREAD

**Issue by boehser-enkel** [ualex73/monitor_docker#85]
Hey there,

from time to time the addon looses connection 
`ERROR (Thread-3) [custom_components.monitor_docker.helpers] [Docker] hassio_observer: Container not available anymore (3) (DockerError(900, 'Cannot connect to Docker Engine via tcp://192.168.88.201:2375 [Server disconnected]'))`

docker -H tcp://192.168.88.201:2375 ps 
gives me data back so there is a connection

How can i solve this?

greetz

**Comment by ualex73** [comment]
This should hopefully be fixed in '1.14-beta3', can you try that version?

**Comment by boehser-enkel** [comment]
i'll try it out

**Comment by boehser-enkel** [comment]
Up until now the connection persists. There is a log error at night saying there is no connection (which bothers me a bit ^^) but the data is there

**Comment by boehser-enkel** [comment]
Works great but also spams the logs as error. Any plans to remove them?

**Comment by ualex73** [comment]
Technically it is not a monitor_docker problem, because the proxy closes the connection and we do a re-establish. I will check if we can introduce an ignore option (something like if you enable it, it does not log anything in any situation).

**Comment by boehser-enkel** [comment]
I configured log level via HA config. That works good

**Comment by ualex73** [comment]
I will close this one, if it persist, please raise a new ticket.
