### ISSUE TITLE
Additional property dockerproxy is not allowed

### ISSUE THREAD

**Issue by X1pheR** [ualex73/monitor_docker#91]
Noobie here. I tried copy&paste to deploy but got the below error. Seemed I missed a version and services attribute in the docker compose but didn't know. Maybe include in the example?

![image](https://user-images.githubusercontent.com/569396/149145367-84a274fa-3a73-49a1-8ba8-869cdce87fa7.png)

**Comment by ualex73** [comment]
Where are you trying to deploy this?

**Comment by ualex73** [comment]
Updated the README, so I will close this one ... if you find more documentation/README improvements, please let me know or draft a PR.
