### ISSUE TITLE
Not in HACS 

### ISSUE THREAD

**Issue by theBasher91** [ualex73/monitor_docker#97]
Apologies, not sure where to ask a question. Monitor docker is not in HACS 1.24.5. Im using home assistant 2022.4.5 in docker on a synology. Is there something I'm perhaps missing?

**Comment by ualex73** [comment]
At this moment I cannot reproduce your issue, I see the monitor docker in the HACS 1.24.5 list, but it can take a while for HACS to update the complete list.

<img width="1027" alt="Schermafbeelding 2022-04-23 om 14 17 28" src="https://user-images.githubusercontent.com/6293852/164894183-a918d6ce-e4de-4387-be03-8fc071f79b92.png">
.

**Comment by theBasher91** [comment]
I reverted to a previous version and upgrade back to what I originally had and it seemed to fix the issue. Thank you for your support
